import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Strapi Project",
  description: "Generated by Next and Strapi CMS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-slate-900 dark:text-white`}>
        <main className="container mx-auto max-w-2xl my-6">{children}</main>
      </body>
    </html>
  );
}
